# 命令级验收包含冻结数据, 两类环境, 续跑与错误参数。
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
function(ok)
  execute_process(COMMAND "${BENCH}" ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "命令失败: ${ARGV}\n${output}\n${error}")
  endif()
endfunction()
function(fails)
  execute_process(COMMAND "${BENCH}" ${ARGV} RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
  if(result EQUAL 0)
    message(FATAL_ERROR "应拒绝的命令成功了: ${ARGV}")
  endif()
endfunction()
ok(generate --env gordon --out "${WORK}/data" --trajectories 2)
foreach(algorithm bpf etpf)
  ok(run --data "${WORK}/data" --out "${WORK}/${algorithm}" --algorithm ${algorithm} --particles 64 --threads 2)
  file(SHA256 "${WORK}/${algorithm}/trajectory-0.bin" before)
  ok(run --data "${WORK}/data" --out "${WORK}/${algorithm}" --algorithm ${algorithm} --particles 64 --threads 2 --resume)
  file(SHA256 "${WORK}/${algorithm}/trajectory-0.bin" after)
  if(NOT before STREQUAL after)
    message(FATAL_ERROR "续跑修改了已完成轨迹")
  endif()
  # 模拟在结果文件提交后, 摘要提交前被中断。
  file(REMOVE "${WORK}/${algorithm}/trajectory-1.bin.sha256")
  ok(run --data "${WORK}/data" --out "${WORK}/${algorithm}" --algorithm ${algorithm} --particles 64 --threads 2 --resume)
  ok(evaluate --data "${WORK}/data" --runs "${WORK}/${algorithm}" --out "${WORK}/${algorithm}-report")
  ok(run --data "${WORK}/data" --out "${WORK}/${algorithm}-serial" --algorithm ${algorithm} --particles 64 --threads 1)
  ok(export --file "${WORK}/${algorithm}/trajectory-0.bin" --out "${WORK}/${algorithm}-parallel.csv")
  ok(export --file "${WORK}/${algorithm}-serial/trajectory-0.bin" --out "${WORK}/${algorithm}-serial.csv")
  file(SHA256 "${WORK}/${algorithm}-parallel.csv" parallel)
  file(SHA256 "${WORK}/${algorithm}-serial.csv" serial)
  if(NOT parallel STREQUAL serial)
    message(FATAL_ERROR "并行调度改变了滤波数值结果")
  endif()
endforeach()
ok(generate --env tracking --out "${WORK}/tracking" --trajectories 1 --variant matched-prior)
foreach(algorithm bpf etpf)
  ok(run --data "${WORK}/tracking" --out "${WORK}/tracking-${algorithm}" --algorithm ${algorithm} --particles 32)
  ok(evaluate --data "${WORK}/tracking" --runs "${WORK}/tracking-${algorithm}" --out "${WORK}/tracking-${algorithm}-report")
endforeach()
ok(export --file "${WORK}/bpf/trajectory-0.bin" --out "${WORK}/means.csv")
fails(run --data "${WORK}/data" --out "${WORK}/bad" --particles 0)
fails(run --data "${WORK}/data" --out "${WORK}/bpf" --algorithm bpf --particles 65 --resume)
fails(generate --env gordon --out "${WORK}/data")
fails(generate --out "${WORK}/typo" --trajectoreis 1)
