# 自定义噪声数据必须自行携带似然配置, run 不接受另行覆盖噪声。
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
function(ok)
  execute_process(COMMAND "${BENCH}" ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "噪声命令失败: ${ARGV}\n${output}\n${error}")
  endif()
endfunction()
function(fails)
  execute_process(COMMAND "${BENCH}" ${ARGV} RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
  if(result EQUAL 0)
    message(FATAL_ERROR "应拒绝的噪声配置被接受: ${ARGV}")
  endif()
endfunction()
ok(generate --env gordon --out "${WORK}/gordon" --trajectories 1
  --process-noise uniform --process-dim 1 --process-lower -0.1 --process-upper 0.1
  --observation-noise uniform --observation-lower -10000 --observation-upper 10000)
ok(generate --env tracking --out "${WORK}/tracking" --trajectories 1
  --process-noise normal --process-dim 2 --process-mean 0.0001,-0.0001 --process-std 0.001,0.002
  --observation-noise normal --observation-dim 1 --observation-mean 0.01 --observation-std 0.5)
foreach(environment gordon tracking)
  foreach(algorithm bpf etpf)
    ok(run --data "${WORK}/${environment}" --out "${WORK}/${environment}-${algorithm}" --algorithm ${algorithm} --particles 64)
    ok(run --data "${WORK}/${environment}" --out "${WORK}/${environment}-${algorithm}" --algorithm ${algorithm} --particles 64 --resume)
    ok(evaluate --data "${WORK}/${environment}" --runs "${WORK}/${environment}-${algorithm}" --out "${WORK}/${environment}-${algorithm}-report")
  endforeach()
endforeach()
fails(generate --out "${WORK}/bad-dim" --process-dim 2)
fails(generate --out "${WORK}/bad-std" --process-std 0)
fails(generate --out "${WORK}/bad-list" --env tracking --process-std 1,2,3)
fails(generate --out "${WORK}/bad-kind" --process-noise uniform --process-std 1)
fails(generate --out "${WORK}/bad-bound" --process-noise uniform --process-lower 1 --process-upper -1)
fails(run --data "${WORK}/gordon" --out "${WORK}/override" --process-noise normal)
